GIFTed/Models/Receivers.cs
using System;
using System.Collections.Generic;
using System.Linq;
using GIFTed.Areas.Identity.Data;
using GIFTed.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using System.ComponentModel.DataAnnotations.Schema;

namespace GIFTed.Models
{
    public class Receivers
    {
        private UserManager<GIFTedUser> userManager;
        private ReceiversDbContext context;

        public Receivers(UserManager<GIFTedUser> usrMgr, ReceiversDbContext dbContext)
        {
            userManager = usrMgr;
            context = dbContext;
        }


        public int Id { get; set; }
        public string Name { get; set; }

        public DateTime today = DateTime.Today;
        public DateTime Birthday { get; set; }
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime NextBirthday
        {
            get => new DateTime(today.Year, Birthday.Month, Birthday.Day);
            private set { }
        }
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public int Countdown
        {
            get => (NextBirthday - DateTime.Today).Days;
            private set { }
        }

        public string Address { get; set; }
        public string ContactEmail { get; set; }
        public RelationshipType Type { get; set; }
        public string Notes { get; set; }

        public List<Gift> gifts { get; set; }

        
        public string UserId { get; set; }

        public Receivers()
        {
        }

        public Receivers(string name, DateTime birthday, DateTime nextBirthday, int countdown, string address, string contactemail, string notes, List<Gift> gifts)
        {
            Name = name;
            Birthday = birthday;
            NextBirthday = nextBirthday;
            Countdown = countdown;
            Address = address;
            ContactEmail = contactemail;
            Notes = notes;
            gifts = context.Gift
                .Where(g => g.ReceiverId == Id)
                .ToList();
        }

        public override string ToString()
        {
            return Name;
        }
    }
}

GIFTed/Controllers/ReceiverController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using GIFTed.Data;
using GIFTed.Models;
using GIFTed.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using GIFTed.Areas.Identity.Data;

namespace GIFTed.Controllers
{
    [Authorize]
    public class ReceiverController : Controller
    {
        private UserManager<GIFTedUser> userManager;
        private ReceiversDbContext context;

        public ReceiverController(UserManager<GIFTedUser> usrMgr, ReceiversDbContext dbContext)
        {
            userManager = usrMgr;
            context = dbContext;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            List<Receivers> receivers = context.Receivers
                .Where(i => i.UserId == userManager.GetUserAsync(User).Result.Id)
                .ToList();


            return View(receivers);
        }

     
        public IActionResult Add()
        {
            AddReceiverViewModel addReceiverViewModel = new AddReceiverViewModel();
            return View(addReceiverViewModel);
        }



        [HttpPost]
        public IActionResult Add(AddReceiverViewModel addReceiverViewModel)
        {
            if (ModelState.IsValid)
            {
                Receivers newReceiver = new Receivers
                {
                    Name = addReceiverViewModel.Name,
                    Birthday = addReceiverViewModel.Birthday,
                    Address = addReceiverViewModel.Address,
                    ContactEmail = addReceiverViewModel.ContactEmail,
                    Type = addReceiverViewModel.Type,
                    Notes = addReceiverViewModel.Notes,
                    UserId = userManager.GetUserAsync(User).Result.Id,
                };

                context.Receivers.Add(newReceiver);
                context.SaveChanges();

                return Redirect("/Receiver");
            }
            return View(addReceiverViewModel);
        }

        public IActionResult Delete(int Id)
        {
            Receivers theReceiver = context.Receivers.Find(Id);
            context.Remove(theReceiver);
            context.SaveChanges();

            return Redirect("/Receiver");
        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {

            Receivers theReceiver = context.Receivers.Find(Id);
            AddReceiverViewModel addReceiverViewModel = new AddReceiverViewModel
            {
                Name = theReceiver.Name,
                Birthday = theReceiver.Birthday,
                ContactEmail = theReceiver.ContactEmail,
                Address = theReceiver.Address,
                Type = theReceiver.Type,
                Notes = theReceiver.Notes,
            };

            return View(addReceiverViewModel);
        }

        [HttpPost]
        public IActionResult Edit(int Id, [Bind("Id,Name,Birthday,ContactEmail,Address,Type,Notes")] AddReceiverViewModel addReceiverViewModel)
        {
            Receivers theReceiver = context.Receivers.Find(Id);

            if (ModelState.IsValid)
            {
                theReceiver.Name = addReceiverViewModel.Name;
                theReceiver.Birthday = addReceiverViewModel.Birthday;
                theReceiver.ContactEmail = addReceiverViewModel.ContactEmail;
                theReceiver.Address = addReceiverViewModel.Address;
                theReceiver.Type = addReceiverViewModel.Type;
                theReceiver.Notes = addReceiverViewModel.Notes;


                context.Update(theReceiver);
                context.SaveChanges();

            }
            
            return Redirect("/Receiver");
        }
            


    }
}

GIFTed/Views/Receiver/Edit.cshtml
@using GIFTed.ViewModels;
@model AddReceiverViewModel;

<h1>Edit Receiver</h1>

<form asp-controller="Receiver" asp-action="Edit" method="post">
    <div class="form-group">
        <label asp-for="Name">Receiver Name</label>
        <input class="form-control" asp-for="Name" value="@Model.Name"/>
        <span asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="Birthday">Receiver Birthday</label>
        <input class="form-control" asp-for="Birthday" value="@Model.Birthday"/>
        <span asp-validation-for="Birthday"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address">Receiver Address</label>
        <input class="form-control" asp-for="Address" value="@Model.Address"/>
        <span asp-validation-for="Address"></span>
    </div>
    <div class="form-group">
        <label asp-for="ContactEmail">Receiver Email Address</label>
        <input class="form-control" id="exampleInputEmail" placeholder="Enter email" asp-for="ContactEmail" value="@Model.ContactEmail" />
        <span asp-validation-for="ContactEmail"></span>
    </div>
    <div class="form-group">
        <label asp-for="Type">Relationship Type</label>
        <select class="form-control" id="exampleSelect1" asp-for="Type" value="@Model.Type" asp-items="Model.RelationshipTypes"></select>
    </div>
    <div class="form-group">
        <label asp-for="Notes">Notes</label>
        <textarea class="form-control" id="exampleTextarea" rows="10" asp-for="Notes" value="@Model.Notes">Add Notes</textarea>
    </div>
    <input role="button" type="submit" class="btn btn-primary" value="Save" />
</form>