GIFTed/Models/Gift.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GIFTed.Models
{
    public class Gift
    {
        public int Id { get; set; }
        public string GiftName { get; set; }
        public float Cost { get; set; }
        public string Link { get; set; }

        public Receivers Receiver { get; set; }
        public int ReceiverId { get; set; }

        public Gift(string giftName, float cost, string link)
        {
            GiftName = giftName;
            Cost = cost;
            Link = link;
        }

        public Gift()
        {
        }

        public override bool Equals(object obj)
        {
            return obj is Gift gift &&
                   Id == gift.Id;
        }

        public override int GetHashCode()
        {
            return HashCode.Combine(Id);
        }


    }
}

GIFTed/Controllers/GiftController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using GIFTed.Areas.Identity.Data;
using GIFTed.Data;
using GIFTed.Models;
using GIFTed.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GIFTed.Controllers
{
    [Authorize]
    public class GiftController : Controller
    {
        private UserManager<GIFTedUser> userManager;
        private ReceiversDbContext context;

        public GiftController(UserManager<GIFTedUser> usrMgr, ReceiversDbContext dbContext)
        {
            userManager = usrMgr;
            context = dbContext;
        }

        [HttpGet]
        public IActionResult Index()
        {
            List<Gift> gifts = context.Gift
                .Include(e => e.Receiver)
                .Where(i => i.Receiver.UserId == userManager.GetUserAsync(User).Result.Id)
                .ToList();
            return View(gifts);
        }

        public IActionResult Add()
        {
            List<Receivers> receivers = context.Receivers
                .Where(i => i.UserId == userManager.GetUserAsync(User).Result.Id)
                .ToList();
            AddGiftViewModel addGiftViewModel = new AddGiftViewModel(receivers);
            return View(addGiftViewModel);
        }

        [HttpPost]
        public IActionResult Add(AddGiftViewModel addGiftViewModel)
        {
            if (ModelState.IsValid)
            {
                Receivers theReceiver = context.Receivers.Find(addGiftViewModel.ReceiverId);
                Gift newGift = new Gift
                {
                    GiftName = addGiftViewModel.GiftName,
                    Cost = addGiftViewModel.Cost,
                    Link = addGiftViewModel.Link,
                    Receiver = theReceiver,
                };

                context.Gift.Add(newGift);
                context.SaveChanges();

                return Redirect("/Receiver/Index");
            }

            return View(addGiftViewModel);
        }

      
        public IActionResult Delete(int Id)
        {
            Gift theGift = context.Gift.Find(Id);
            context.Gift.Remove(theGift);
            context.SaveChanges();
            return Redirect("/Gift");
        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            Gift editGift = context.Gift.Find(Id);
            List<Receivers> receivers = context.Receivers
                .Where(i => i.UserId == userManager.GetUserAsync(User).Result.Id)
                .ToList();
            AddGiftViewModel addGiftViewModel = new AddGiftViewModel(receivers)
            {
                GiftName = editGift.GiftName,
                Cost = editGift.Cost,
                Link = editGift.Link,
 
            };
            return View(addGiftViewModel);
        }

        [HttpPost]
        public IActionResult Edit(int Id, [Bind("GiftName,Cost,Link,ReceiverId")] AddGiftViewModel addGiftViewModel)
        {
            Gift theGift = context.Gift.Find(Id);

            if (ModelState.IsValid)
            {
                theGift.GiftName = addGiftViewModel.GiftName;
                theGift.Cost = addGiftViewModel.Cost;
                theGift.Link = addGiftViewModel.Link;
                theGift.ReceiverId = addGiftViewModel.ReceiverId;


                context.Gift.Update(theGift);
                context.SaveChanges();
            }
            return Redirect("/Gift");
        }


    }
}

GIFTed/Views/Gift/Edit.cshtml
@using GIFTed.ViewModels;
@model GIFTed.ViewModels.AddGiftViewModel;


<h1>Edit Gift</h1>

<form asp-controller="Gift" asp-action="Edit" method="post">
    <div class="form-group">
        <label asp-for="GiftName">Gift Name</label>
        <input class="form-control" asp-for="GiftName" value="@Model.GiftName" />
        <span asp-validation-for="GiftName"></span>
    </div>
    <div class="form-group">
        <label class="control-label" asp-for="Cost">Cost (to the nearest dollar)</label>
        <div class="form-group">
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" asp-validation-for="Cost">$</span>
                </div>
                <input type="text" class="form-control" aria-label="Amount (to the nearest dollar)" asp-for="Cost" value="@Model.Cost"/>
                <div class="input-group-append">
                    <span class="input-group-text">.00</span>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Link">Link</label>
        <input class="form-control" asp-for="Link" value="@Model.Link" />
        <span asp-validation-for="Link"></span>
    </div>
    <div class="form-group">
        <label asp-for="ReceiverId">Receiver</label>
        <select class="form-control" id="exampleSelect1" asp-for="ReceiverId" asp-items="@Model.Receivers"></select>
    </div>
    <input role="button" type="submit" class="btn btn-primary" value="Save" />
</form>

GIFTed/Views/Gift/Index.cshtml
@model List<GIFTed.Models.Gift>

<h1>All Gifts</h1>


<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            Cost
        </th>
        <th>
            Link
        </th>
        <th>
            Reciever
        </th>
    </tr>


    @foreach (var item in Model)
    {
<tr>
    <td>@item.GiftName</td>
    <td>$@item.Cost</td>
    <td><a role="button" class="btn btn-link" href="@item.Link" target="_blank">Buy Now!</a></td>
    <td>@item.Receiver.Name</td>
    <td><a class="btn btn-outline-primary" asp-controller="Gift" asp-action="Edit" asp-route-id="@item.Id">Edit Gift</a>
        <a class="btn btn-outline-danger" asp-controller="Gift" asp-action="Delete" asp-route-id="@item.Id">Delete Gift</a></td>
</tr>
    }
</table>



<p>
    <a role="button" class="btn btn-outline-warning btn-lg btn-block" asp-controller="Gift" asp-action="Add">Add New Item</a>
</p>